export enum AreaAtuacao {
  MORRO_SANTIAGO = 'QUADRANTE MORRO SANTIAGO',
  RUA_GRITO_ALERTA = 'QUADRANTE RUA GRITO DE ALERTA',
  AV_ROBERT_KENNEDY = 'QUADRANTE AV ROBERT KENNEDY',
  PIRAMBU = 'QUADRANTE PIRAMBU',
  CRISTO_REDENTOR = 'QUADRANTE CRISTO REDENTOR',
}
